name: Build paper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04
    container: ghcr.io/weinshel/typeset:main

    steps:
    - uses: actions/checkout@v4

    - name: compile paper
      run: make
      working-directory: ./paper

    - uses: actions/upload-artifact@v4
      with:
        name: paper
        path: paper/paper.pdf
